ORDER_CONTROLLER_BASE_PATH = "/api/v1/orders"

ORDER_WAITING_TIME = 1


ORDER_CONTROLLER_BUY_PATH = ORDER_CONTROLLER_BASE_PATH + ":buy"
ORDER_CONTROLLER_SELL_PATH = ORDER_CONTROLLER_BASE_PATH + ":sell"
ORDER_CONTROLLER_CANCEL_PATH = ORDER_CONTROLLER_BASE_PATH + ":cancel"
