errors = {
    1000: "Model validation error",
    1100: "Unprocessable entity",
    1101: "Could not contact provider service",
    1200: "Not Authenticated",
    1201: "Permission Denied",
    1300: "Infra Exceptions",
    1999: "Unhandled error",
    2000: "Queue connection lost",
    2001: "Unexpected error for Queue",
    2002: "Publish event unexpected error for OrderEventProducer",
    2003: "User with the given user id is not found",
    2004: "Stock with the given stock symbol is already exists",
    2005: "Stock with the given stock symbol is not found",
    2006: "User balance does not enough for buying",
    2007: "User stock amount does not enough for selling",
    2008: "Unexpected error for creating buy order",
    2009: "Unexpected error for creating sell order",
    2010: "Unexpected error for creating cancel order",
    2011: "Order with the given order id is not found",
    2012: "Order cancel request did not complete with the given order id because of the order was completed",
    2013: "Order cancel request did not complete with the given order id because of the order was failed",
    2014: "Order cancel request did not complete with the given order id because of the order was canceled",
    2015: "Publish event unexpected error for NotificationEventProducer",
}

SYSYEM_ERROR_CODES = [2008, 2009, 2010]
